export const dashboard = {
  ADD_TRANSACTION : "ADD_TRANSACTION",
  SAVE_TRANSACTION : "SAVE_TRANSACTION",
  CLOSE_MODAL : "CLOSE_MODAL",
  SUMMARY : "SUMMARY",
}
export const summary = {
  PURCHASES : "PURCHASES",
  SALES : "SALES",
  OPENINGS : "OPENINGS",
  SUMMARY_ERROR : "SUMMARY_ERROR",
  CLOSE_MODAL : "CLOSE_MODAL"
}
